apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-generator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-generator
  minReplicas: 1
  maxReplicas: 50
  metrics:
  - type: Pods
    pods:
      metric:
        name: generator_bytes_produced_total
      target:
        type: AverageValue
        averageValue: 125000
